name: uco

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - pytest
  - flake8
  - rope
  - autopep8
  - click
  - jupyter
  - pyyaml
  - pytorch=1.2
  - torchvision
  - cudatoolkit=10.0
  - tensorflow
  - tensorboard>=1.14
  - absl-py
  - future
  - tqdm
  - scikit-learn
  - kaggle
  - pre-commit
  - black
  - pip
  - pip:
    - albumentations
    - safitty
    - efficientnet_pytorch
    - git+https://github.com/qubvel/ttach
    - -e .  # install package in development mode
